sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBke5FcyZtBoP1UB5J5
    access-key-secret: 1kZ7ETqwLH2dmQlwffKfw5zaW4LhFj
    bucket-name: lelehmleadnews
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 3